###
@xsuaaHostname=https://4151765etrial.authentication.us10.hana.ondemand.com
@btpXsuaaClient=sb-cf-python-security!t250081
@btpXsuaaSecret=4+GY7Uhe2hTpD8K4Aw3JXrrmKrM=


# @name getXsuaaToken
POST {{xsuaaHostname}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{btpXsuaaClient}}:{{btpXsuaaSecret}}

client_id={{btpXsuaaClient}}
&client_secret={{btpXsuaaSecret}}
&grant_type=client_credentials


###
@access_token = {{getXsuaaToken.response.body.$.access_token}}
@apiEndpointBtp=https://4151765etrial-dev-cf-python-security.cfapps.us10-001.hana.ondemand.com

# @name apiPythonCall
GET {{apiEndpointBtp}}/
Authorization: Bearer {{access_token}}
Content-type: application/json
